export const APP_ACTION_TYPE = {
  SET_HEADER_TEXT: "SET_HEADER_TEXT",
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING",
  SHOW_OVERLAY: "SHOW_OVERLAY",
  HIDE_OVERLAY: "HIDE_OVERLAY"
};

export const LOCALE_ACTION_TYPE = {
  CHANGE_LOCATE_SUCCESS: "CHANGE_LOCATE_SUCCESS"
};

export const FLIGHT_FORM_ACTION_TYPE = {
  FLIGHT_FORM_VALUE_CHANGE: "FLIGHT_FORM_VALUE_CHANGE",
};